name: "Build Release"
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - {
        name: "Set up JDK 21",
        uses: actions/setup-java@v2,
        with: { distribution: "adopt", java-version: "21" },
      }
      - {
        name: "Build with Gradle",
        id: build,
        run: "chmod +x gradlew && ./gradlew build publish",
      }
      - name: "Upload to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "build/libs/opolisutilities-1.21-${mod_version}.jar"
          game_endpoint: "minecraft"
          relations: "neoforge-api:requiredDependency"
          game_versions: "Minecraft 1.21:1.21.1,Java 21,NeoForge"
          project_id: "649644"
          token: "7edd171b-fa2a-43eb-87a1-b5a32d4ee835"